name: suts
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - anndata
      - session-info
      - scanpy[leiden]>=1.10.1
      - jupyterlab>=4.1.6
      - notebook>=7.1.3
      - pytometry>=0.1.4
      - vitessce[all]>=3.2.5
      - zarr>=2.17.2
      - dask-labextension>=7.0.0
      - dask[complete]>=2024.4.2
